// Code generated by protoc-gen-go.
// source: Execution.proto
// DO NOT EDIT!

package contester_proto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RedirectParameters struct {
	Filename         *string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Memory           *bool   `protobuf:"varint,2,opt,name=memory" json:"memory,omitempty"`
	Buffer           *Blob   `protobuf:"bytes,3,opt,name=buffer" json:"buffer,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RedirectParameters) Reset()         { *m = RedirectParameters{} }
func (m *RedirectParameters) String() string { return proto.CompactTextString(m) }
func (*RedirectParameters) ProtoMessage()    {}

func (m *RedirectParameters) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *RedirectParameters) GetMemory() bool {
	if m != nil && m.Memory != nil {
		return *m.Memory
	}
	return false
}

func (m *RedirectParameters) GetBuffer() *Blob {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type ExecutionResultFlags struct {
	Killed             *bool  `protobuf:"varint,1,opt,name=killed" json:"killed,omitempty"`
	TimeLimitHit       *bool  `protobuf:"varint,2,opt,name=time_limit_hit" json:"time_limit_hit,omitempty"`
	MemoryLimitHit     *bool  `protobuf:"varint,3,opt,name=memory_limit_hit" json:"memory_limit_hit,omitempty"`
	Inactive           *bool  `protobuf:"varint,4,opt,name=inactive" json:"inactive,omitempty"`
	TimeLimitHard      *bool  `protobuf:"varint,5,opt,name=time_limit_hard" json:"time_limit_hard,omitempty"`
	StdoutOverflow     *bool  `protobuf:"varint,6,opt,name=stdout_overflow" json:"stdout_overflow,omitempty"`
	StderrOverflow     *bool  `protobuf:"varint,7,opt,name=stderr_overflow" json:"stderr_overflow,omitempty"`
	StdpipeTimeout     *bool  `protobuf:"varint,8,opt,name=stdpipe_timeout" json:"stdpipe_timeout,omitempty"`
	TimeLimitHitPost   *bool  `protobuf:"varint,9,opt,name=time_limit_hit_post" json:"time_limit_hit_post,omitempty"`
	MemoryLimitHitPost *bool  `protobuf:"varint,10,opt,name=memory_limit_hit_post" json:"memory_limit_hit_post,omitempty"`
	ProcessLimitHit    *bool  `protobuf:"varint,11,opt,name=process_limit_hit" json:"process_limit_hit,omitempty"`
	StoppedBySignal    *bool  `protobuf:"varint,12,opt,name=stopped_by_signal" json:"stopped_by_signal,omitempty"`
	KilledBySignal     *bool  `protobuf:"varint,13,opt,name=killed_by_signal" json:"killed_by_signal,omitempty"`
	XXX_unrecognized   []byte `json:"-"`
}

func (m *ExecutionResultFlags) Reset()         { *m = ExecutionResultFlags{} }
func (m *ExecutionResultFlags) String() string { return proto.CompactTextString(m) }
func (*ExecutionResultFlags) ProtoMessage()    {}

func (m *ExecutionResultFlags) GetKilled() bool {
	if m != nil && m.Killed != nil {
		return *m.Killed
	}
	return false
}

func (m *ExecutionResultFlags) GetTimeLimitHit() bool {
	if m != nil && m.TimeLimitHit != nil {
		return *m.TimeLimitHit
	}
	return false
}

func (m *ExecutionResultFlags) GetMemoryLimitHit() bool {
	if m != nil && m.MemoryLimitHit != nil {
		return *m.MemoryLimitHit
	}
	return false
}

func (m *ExecutionResultFlags) GetInactive() bool {
	if m != nil && m.Inactive != nil {
		return *m.Inactive
	}
	return false
}

func (m *ExecutionResultFlags) GetTimeLimitHard() bool {
	if m != nil && m.TimeLimitHard != nil {
		return *m.TimeLimitHard
	}
	return false
}

func (m *ExecutionResultFlags) GetStdoutOverflow() bool {
	if m != nil && m.StdoutOverflow != nil {
		return *m.StdoutOverflow
	}
	return false
}

func (m *ExecutionResultFlags) GetStderrOverflow() bool {
	if m != nil && m.StderrOverflow != nil {
		return *m.StderrOverflow
	}
	return false
}

func (m *ExecutionResultFlags) GetStdpipeTimeout() bool {
	if m != nil && m.StdpipeTimeout != nil {
		return *m.StdpipeTimeout
	}
	return false
}

func (m *ExecutionResultFlags) GetTimeLimitHitPost() bool {
	if m != nil && m.TimeLimitHitPost != nil {
		return *m.TimeLimitHitPost
	}
	return false
}

func (m *ExecutionResultFlags) GetMemoryLimitHitPost() bool {
	if m != nil && m.MemoryLimitHitPost != nil {
		return *m.MemoryLimitHitPost
	}
	return false
}

func (m *ExecutionResultFlags) GetProcessLimitHit() bool {
	if m != nil && m.ProcessLimitHit != nil {
		return *m.ProcessLimitHit
	}
	return false
}

func (m *ExecutionResultFlags) GetStoppedBySignal() bool {
	if m != nil && m.StoppedBySignal != nil {
		return *m.StoppedBySignal
	}
	return false
}

func (m *ExecutionResultFlags) GetKilledBySignal() bool {
	if m != nil && m.KilledBySignal != nil {
		return *m.KilledBySignal
	}
	return false
}

type ExecutionResultTime struct {
	UserTimeMicros   *uint64 `protobuf:"varint,1,opt,name=user_time_micros" json:"user_time_micros,omitempty"`
	KernelTimeMicros *uint64 `protobuf:"varint,2,opt,name=kernel_time_micros" json:"kernel_time_micros,omitempty"`
	WallTimeMicros   *uint64 `protobuf:"varint,3,opt,name=wall_time_micros" json:"wall_time_micros,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExecutionResultTime) Reset()         { *m = ExecutionResultTime{} }
func (m *ExecutionResultTime) String() string { return proto.CompactTextString(m) }
func (*ExecutionResultTime) ProtoMessage()    {}

func (m *ExecutionResultTime) GetUserTimeMicros() uint64 {
	if m != nil && m.UserTimeMicros != nil {
		return *m.UserTimeMicros
	}
	return 0
}

func (m *ExecutionResultTime) GetKernelTimeMicros() uint64 {
	if m != nil && m.KernelTimeMicros != nil {
		return *m.KernelTimeMicros
	}
	return 0
}

func (m *ExecutionResultTime) GetWallTimeMicros() uint64 {
	if m != nil && m.WallTimeMicros != nil {
		return *m.WallTimeMicros
	}
	return 0
}

func init() {
}
