// Code generated by protoc-gen-go.
// source: Local.proto
// DO NOT EDIT!

package contester_proto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type BinaryTypeResponse_Win32BinaryType int32

const (
	BinaryTypeResponse_SCS_32BIT_BINARY BinaryTypeResponse_Win32BinaryType = 0
	BinaryTypeResponse_SCS_DOS_BINARY   BinaryTypeResponse_Win32BinaryType = 1
	BinaryTypeResponse_SCS_WOW_BINARY   BinaryTypeResponse_Win32BinaryType = 2
	BinaryTypeResponse_SCS_PIF_BINARY   BinaryTypeResponse_Win32BinaryType = 3
	BinaryTypeResponse_SCS_POSIX_BINARY BinaryTypeResponse_Win32BinaryType = 4
	BinaryTypeResponse_SCS_OS216_BINARY BinaryTypeResponse_Win32BinaryType = 5
	BinaryTypeResponse_SCS_64BIT_BINARY BinaryTypeResponse_Win32BinaryType = 6
)

var BinaryTypeResponse_Win32BinaryType_name = map[int32]string{
	0: "SCS_32BIT_BINARY",
	1: "SCS_DOS_BINARY",
	2: "SCS_WOW_BINARY",
	3: "SCS_PIF_BINARY",
	4: "SCS_POSIX_BINARY",
	5: "SCS_OS216_BINARY",
	6: "SCS_64BIT_BINARY",
}
var BinaryTypeResponse_Win32BinaryType_value = map[string]int32{
	"SCS_32BIT_BINARY": 0,
	"SCS_DOS_BINARY":   1,
	"SCS_WOW_BINARY":   2,
	"SCS_PIF_BINARY":   3,
	"SCS_POSIX_BINARY": 4,
	"SCS_OS216_BINARY": 5,
	"SCS_64BIT_BINARY": 6,
}

func (x BinaryTypeResponse_Win32BinaryType) Enum() *BinaryTypeResponse_Win32BinaryType {
	p := new(BinaryTypeResponse_Win32BinaryType)
	*p = x
	return p
}
func (x BinaryTypeResponse_Win32BinaryType) String() string {
	return proto.EnumName(BinaryTypeResponse_Win32BinaryType_name, int32(x))
}
func (x BinaryTypeResponse_Win32BinaryType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *BinaryTypeResponse_Win32BinaryType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BinaryTypeResponse_Win32BinaryType_value, data, "BinaryTypeResponse_Win32BinaryType")
	if err != nil {
		return err
	}
	*x = BinaryTypeResponse_Win32BinaryType(value)
	return nil
}

type LocalEnvironment struct {
	Empty            *bool                        `protobuf:"varint,1,opt,name=empty" json:"empty,omitempty"`
	Variable         []*LocalEnvironment_Variable `protobuf:"bytes,2,rep,name=variable" json:"variable,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *LocalEnvironment) Reset()         { *m = LocalEnvironment{} }
func (m *LocalEnvironment) String() string { return proto.CompactTextString(m) }
func (*LocalEnvironment) ProtoMessage()    {}

func (m *LocalEnvironment) GetEmpty() bool {
	if m != nil && m.Empty != nil {
		return *m.Empty
	}
	return false
}

func (m *LocalEnvironment) GetVariable() []*LocalEnvironment_Variable {
	if m != nil {
		return m.Variable
	}
	return nil
}

type LocalEnvironment_Variable struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Expand           *bool   `protobuf:"varint,3,opt,name=expand" json:"expand,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LocalEnvironment_Variable) Reset()         { *m = LocalEnvironment_Variable{} }
func (m *LocalEnvironment_Variable) String() string { return proto.CompactTextString(m) }
func (*LocalEnvironment_Variable) ProtoMessage()    {}

func (m *LocalEnvironment_Variable) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *LocalEnvironment_Variable) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *LocalEnvironment_Variable) GetExpand() bool {
	if m != nil && m.Expand != nil {
		return *m.Expand
	}
	return false
}

type LocalExecutionParameters struct {
	ApplicationName       *string             `protobuf:"bytes,1,opt,name=application_name" json:"application_name,omitempty"`
	CommandLine           *string             `protobuf:"bytes,2,opt,name=command_line" json:"command_line,omitempty"`
	CurrentDirectory      *string             `protobuf:"bytes,3,opt,name=current_directory" json:"current_directory,omitempty"`
	TimeLimitMicros       *uint64             `protobuf:"varint,4,opt,name=time_limit_micros" json:"time_limit_micros,omitempty"`
	MemoryLimit           *uint64             `protobuf:"varint,5,opt,name=memory_limit" json:"memory_limit,omitempty"`
	CheckIdleness         *bool               `protobuf:"varint,6,opt,name=check_idleness" json:"check_idleness,omitempty"`
	Environment           *LocalEnvironment   `protobuf:"bytes,7,opt,name=environment" json:"environment,omitempty"`
	RestrictUi            *bool               `protobuf:"varint,8,opt,name=restrict_ui" json:"restrict_ui,omitempty"`
	NoJob                 *bool               `protobuf:"varint,9,opt,name=no_job" json:"no_job,omitempty"`
	ProcessLimit          *uint32             `protobuf:"varint,10,opt,name=process_limit" json:"process_limit,omitempty"`
	TimeLimitHardMicros   *uint64             `protobuf:"varint,15,opt,name=time_limit_hard_micros" json:"time_limit_hard_micros,omitempty"`
	StdIn                 *RedirectParameters `protobuf:"bytes,12,opt,name=std_in" json:"std_in,omitempty"`
	StdOut                *RedirectParameters `protobuf:"bytes,13,opt,name=std_out" json:"std_out,omitempty"`
	StdErr                *RedirectParameters `protobuf:"bytes,14,opt,name=std_err" json:"std_err,omitempty"`
	CommandLineParameters []string            `protobuf:"bytes,16,rep,name=command_line_parameters" json:"command_line_parameters,omitempty"`
	SandboxId             *string             `protobuf:"bytes,17,opt,name=sandbox_id" json:"sandbox_id,omitempty"`
	XXX_unrecognized      []byte              `json:"-"`
}

func (m *LocalExecutionParameters) Reset()         { *m = LocalExecutionParameters{} }
func (m *LocalExecutionParameters) String() string { return proto.CompactTextString(m) }
func (*LocalExecutionParameters) ProtoMessage()    {}

func (m *LocalExecutionParameters) GetApplicationName() string {
	if m != nil && m.ApplicationName != nil {
		return *m.ApplicationName
	}
	return ""
}

func (m *LocalExecutionParameters) GetCommandLine() string {
	if m != nil && m.CommandLine != nil {
		return *m.CommandLine
	}
	return ""
}

func (m *LocalExecutionParameters) GetCurrentDirectory() string {
	if m != nil && m.CurrentDirectory != nil {
		return *m.CurrentDirectory
	}
	return ""
}

func (m *LocalExecutionParameters) GetTimeLimitMicros() uint64 {
	if m != nil && m.TimeLimitMicros != nil {
		return *m.TimeLimitMicros
	}
	return 0
}

func (m *LocalExecutionParameters) GetMemoryLimit() uint64 {
	if m != nil && m.MemoryLimit != nil {
		return *m.MemoryLimit
	}
	return 0
}

func (m *LocalExecutionParameters) GetCheckIdleness() bool {
	if m != nil && m.CheckIdleness != nil {
		return *m.CheckIdleness
	}
	return false
}

func (m *LocalExecutionParameters) GetEnvironment() *LocalEnvironment {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *LocalExecutionParameters) GetRestrictUi() bool {
	if m != nil && m.RestrictUi != nil {
		return *m.RestrictUi
	}
	return false
}

func (m *LocalExecutionParameters) GetNoJob() bool {
	if m != nil && m.NoJob != nil {
		return *m.NoJob
	}
	return false
}

func (m *LocalExecutionParameters) GetProcessLimit() uint32 {
	if m != nil && m.ProcessLimit != nil {
		return *m.ProcessLimit
	}
	return 0
}

func (m *LocalExecutionParameters) GetTimeLimitHardMicros() uint64 {
	if m != nil && m.TimeLimitHardMicros != nil {
		return *m.TimeLimitHardMicros
	}
	return 0
}

func (m *LocalExecutionParameters) GetStdIn() *RedirectParameters {
	if m != nil {
		return m.StdIn
	}
	return nil
}

func (m *LocalExecutionParameters) GetStdOut() *RedirectParameters {
	if m != nil {
		return m.StdOut
	}
	return nil
}

func (m *LocalExecutionParameters) GetStdErr() *RedirectParameters {
	if m != nil {
		return m.StdErr
	}
	return nil
}

func (m *LocalExecutionParameters) GetCommandLineParameters() []string {
	if m != nil {
		return m.CommandLineParameters
	}
	return nil
}

func (m *LocalExecutionParameters) GetSandboxId() string {
	if m != nil && m.SandboxId != nil {
		return *m.SandboxId
	}
	return ""
}

type LocalExecuteConnected struct {
	First            *LocalExecutionParameters `protobuf:"bytes,1,opt,name=first" json:"first,omitempty"`
	Second           *LocalExecutionParameters `protobuf:"bytes,2,opt,name=second" json:"second,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *LocalExecuteConnected) Reset()         { *m = LocalExecuteConnected{} }
func (m *LocalExecuteConnected) String() string { return proto.CompactTextString(m) }
func (*LocalExecuteConnected) ProtoMessage()    {}

func (m *LocalExecuteConnected) GetFirst() *LocalExecutionParameters {
	if m != nil {
		return m.First
	}
	return nil
}

func (m *LocalExecuteConnected) GetSecond() *LocalExecutionParameters {
	if m != nil {
		return m.Second
	}
	return nil
}

type LocalExecutionResult struct {
	Flags            *ExecutionResultFlags `protobuf:"bytes,1,opt,name=flags" json:"flags,omitempty"`
	Time             *ExecutionResultTime  `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	Memory           *uint64               `protobuf:"varint,3,opt,name=memory" json:"memory,omitempty"`
	ReturnCode       *uint32               `protobuf:"varint,4,opt,name=return_code" json:"return_code,omitempty"`
	StdOut           *Blob                 `protobuf:"bytes,5,opt,name=std_out" json:"std_out,omitempty"`
	StdErr           *Blob                 `protobuf:"bytes,6,opt,name=std_err" json:"std_err,omitempty"`
	TotalProcesses   *uint64               `protobuf:"varint,7,opt,name=total_processes" json:"total_processes,omitempty"`
	KillSignal       *int32                `protobuf:"varint,8,opt,name=kill_signal" json:"kill_signal,omitempty"`
	StopSignal       *int32                `protobuf:"varint,9,opt,name=stop_signal" json:"stop_signal,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *LocalExecutionResult) Reset()         { *m = LocalExecutionResult{} }
func (m *LocalExecutionResult) String() string { return proto.CompactTextString(m) }
func (*LocalExecutionResult) ProtoMessage()    {}

func (m *LocalExecutionResult) GetFlags() *ExecutionResultFlags {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *LocalExecutionResult) GetTime() *ExecutionResultTime {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *LocalExecutionResult) GetMemory() uint64 {
	if m != nil && m.Memory != nil {
		return *m.Memory
	}
	return 0
}

func (m *LocalExecutionResult) GetReturnCode() uint32 {
	if m != nil && m.ReturnCode != nil {
		return *m.ReturnCode
	}
	return 0
}

func (m *LocalExecutionResult) GetStdOut() *Blob {
	if m != nil {
		return m.StdOut
	}
	return nil
}

func (m *LocalExecutionResult) GetStdErr() *Blob {
	if m != nil {
		return m.StdErr
	}
	return nil
}

func (m *LocalExecutionResult) GetTotalProcesses() uint64 {
	if m != nil && m.TotalProcesses != nil {
		return *m.TotalProcesses
	}
	return 0
}

func (m *LocalExecutionResult) GetKillSignal() int32 {
	if m != nil && m.KillSignal != nil {
		return *m.KillSignal
	}
	return 0
}

func (m *LocalExecutionResult) GetStopSignal() int32 {
	if m != nil && m.StopSignal != nil {
		return *m.StopSignal
	}
	return 0
}

type LocalExecuteConnectedResult struct {
	First            *LocalExecutionResult `protobuf:"bytes,1,opt,name=first" json:"first,omitempty"`
	Second           *LocalExecutionResult `protobuf:"bytes,2,opt,name=second" json:"second,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *LocalExecuteConnectedResult) Reset()         { *m = LocalExecuteConnectedResult{} }
func (m *LocalExecuteConnectedResult) String() string { return proto.CompactTextString(m) }
func (*LocalExecuteConnectedResult) ProtoMessage()    {}

func (m *LocalExecuteConnectedResult) GetFirst() *LocalExecutionResult {
	if m != nil {
		return m.First
	}
	return nil
}

func (m *LocalExecuteConnectedResult) GetSecond() *LocalExecutionResult {
	if m != nil {
		return m.Second
	}
	return nil
}

type LocalExecution struct {
	Parameters       *LocalExecutionParameters `protobuf:"bytes,1,req,name=parameters" json:"parameters,omitempty"`
	Result           *LocalExecutionResult     `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *LocalExecution) Reset()         { *m = LocalExecution{} }
func (m *LocalExecution) String() string { return proto.CompactTextString(m) }
func (*LocalExecution) ProtoMessage()    {}

func (m *LocalExecution) GetParameters() *LocalExecutionParameters {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *LocalExecution) GetResult() *LocalExecutionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type BinaryTypeRequest struct {
	Pathname         *string `protobuf:"bytes,1,opt,name=pathname" json:"pathname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BinaryTypeRequest) Reset()         { *m = BinaryTypeRequest{} }
func (m *BinaryTypeRequest) String() string { return proto.CompactTextString(m) }
func (*BinaryTypeRequest) ProtoMessage()    {}

func (m *BinaryTypeRequest) GetPathname() string {
	if m != nil && m.Pathname != nil {
		return *m.Pathname
	}
	return ""
}

type BinaryTypeResponse struct {
	Failure          *bool                               `protobuf:"varint,1,opt,name=failure" json:"failure,omitempty"`
	Result           *BinaryTypeResponse_Win32BinaryType `protobuf:"varint,2,opt,name=result,enum=contester.proto.BinaryTypeResponse_Win32BinaryType" json:"result,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (m *BinaryTypeResponse) Reset()         { *m = BinaryTypeResponse{} }
func (m *BinaryTypeResponse) String() string { return proto.CompactTextString(m) }
func (*BinaryTypeResponse) ProtoMessage()    {}

func (m *BinaryTypeResponse) GetFailure() bool {
	if m != nil && m.Failure != nil {
		return *m.Failure
	}
	return false
}

func (m *BinaryTypeResponse) GetResult() BinaryTypeResponse_Win32BinaryType {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type ClearSandboxRequest struct {
	Sandbox          *string `protobuf:"bytes,1,opt,name=sandbox" json:"sandbox,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ClearSandboxRequest) Reset()         { *m = ClearSandboxRequest{} }
func (m *ClearSandboxRequest) String() string { return proto.CompactTextString(m) }
func (*ClearSandboxRequest) ProtoMessage()    {}

func (m *ClearSandboxRequest) GetSandbox() string {
	if m != nil && m.Sandbox != nil {
		return *m.Sandbox
	}
	return ""
}

type IdentifyRequest struct {
	ContesterId      *string `protobuf:"bytes,1,opt,name=contester_id" json:"contester_id,omitempty"`
	MongoHost        *string `protobuf:"bytes,2,opt,name=mongo_host" json:"mongo_host,omitempty"`
	MongoDb          *string `protobuf:"bytes,3,opt,name=mongo_db" json:"mongo_db,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IdentifyRequest) Reset()         { *m = IdentifyRequest{} }
func (m *IdentifyRequest) String() string { return proto.CompactTextString(m) }
func (*IdentifyRequest) ProtoMessage()    {}

func (m *IdentifyRequest) GetContesterId() string {
	if m != nil && m.ContesterId != nil {
		return *m.ContesterId
	}
	return ""
}

func (m *IdentifyRequest) GetMongoHost() string {
	if m != nil && m.MongoHost != nil {
		return *m.MongoHost
	}
	return ""
}

func (m *IdentifyRequest) GetMongoDb() string {
	if m != nil && m.MongoDb != nil {
		return *m.MongoDb
	}
	return ""
}

type SandboxLocations struct {
	Compile          *string `protobuf:"bytes,1,opt,name=compile" json:"compile,omitempty"`
	Run              *string `protobuf:"bytes,2,opt,name=run" json:"run,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SandboxLocations) Reset()         { *m = SandboxLocations{} }
func (m *SandboxLocations) String() string { return proto.CompactTextString(m) }
func (*SandboxLocations) ProtoMessage()    {}

func (m *SandboxLocations) GetCompile() string {
	if m != nil && m.Compile != nil {
		return *m.Compile
	}
	return ""
}

func (m *SandboxLocations) GetRun() string {
	if m != nil && m.Run != nil {
		return *m.Run
	}
	return ""
}

type IdentifyResponse struct {
	InvokerId        *string             `protobuf:"bytes,1,opt,name=invoker_id" json:"invoker_id,omitempty"`
	Sandboxes        []*SandboxLocations `protobuf:"bytes,2,rep,name=sandboxes" json:"sandboxes,omitempty"`
	Environment      *LocalEnvironment   `protobuf:"bytes,3,opt,name=environment" json:"environment,omitempty"`
	Platform         *string             `protobuf:"bytes,4,opt,name=platform" json:"platform,omitempty"`
	PathSeparator    *string             `protobuf:"bytes,5,opt,name=path_separator" json:"path_separator,omitempty"`
	Disks            []string            `protobuf:"bytes,6,rep,name=disks" json:"disks,omitempty"`
	ProgramFiles     []string            `protobuf:"bytes,7,rep,name=programFiles" json:"programFiles,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *IdentifyResponse) Reset()         { *m = IdentifyResponse{} }
func (m *IdentifyResponse) String() string { return proto.CompactTextString(m) }
func (*IdentifyResponse) ProtoMessage()    {}

func (m *IdentifyResponse) GetInvokerId() string {
	if m != nil && m.InvokerId != nil {
		return *m.InvokerId
	}
	return ""
}

func (m *IdentifyResponse) GetSandboxes() []*SandboxLocations {
	if m != nil {
		return m.Sandboxes
	}
	return nil
}

func (m *IdentifyResponse) GetEnvironment() *LocalEnvironment {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *IdentifyResponse) GetPlatform() string {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return ""
}

func (m *IdentifyResponse) GetPathSeparator() string {
	if m != nil && m.PathSeparator != nil {
		return *m.PathSeparator
	}
	return ""
}

func (m *IdentifyResponse) GetDisks() []string {
	if m != nil {
		return m.Disks
	}
	return nil
}

func (m *IdentifyResponse) GetProgramFiles() []string {
	if m != nil {
		return m.ProgramFiles
	}
	return nil
}

type FileStat struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	IsDirectory      *bool   `protobuf:"varint,2,opt,name=is_directory" json:"is_directory,omitempty"`
	Size             *uint64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Checksum         *string `protobuf:"bytes,4,opt,name=checksum" json:"checksum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FileStat) Reset()         { *m = FileStat{} }
func (m *FileStat) String() string { return proto.CompactTextString(m) }
func (*FileStat) ProtoMessage()    {}

func (m *FileStat) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *FileStat) GetIsDirectory() bool {
	if m != nil && m.IsDirectory != nil {
		return *m.IsDirectory
	}
	return false
}

func (m *FileStat) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *FileStat) GetChecksum() string {
	if m != nil && m.Checksum != nil {
		return *m.Checksum
	}
	return ""
}

type StatRequest struct {
	Name              []string `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	SandboxId         *string  `protobuf:"bytes,2,opt,name=sandbox_id" json:"sandbox_id,omitempty"`
	Expand            *bool    `protobuf:"varint,3,opt,name=expand" json:"expand,omitempty"`
	CalculateChecksum *bool    `protobuf:"varint,4,opt,name=calculate_checksum" json:"calculate_checksum,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *StatRequest) Reset()         { *m = StatRequest{} }
func (m *StatRequest) String() string { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()    {}

func (m *StatRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *StatRequest) GetSandboxId() string {
	if m != nil && m.SandboxId != nil {
		return *m.SandboxId
	}
	return ""
}

func (m *StatRequest) GetExpand() bool {
	if m != nil && m.Expand != nil {
		return *m.Expand
	}
	return false
}

func (m *StatRequest) GetCalculateChecksum() bool {
	if m != nil && m.CalculateChecksum != nil {
		return *m.CalculateChecksum
	}
	return false
}

type FileStats struct {
	Entries          []*FileStat `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *FileStats) Reset()         { *m = FileStats{} }
func (m *FileStats) String() string { return proto.CompactTextString(m) }
func (*FileStats) ProtoMessage()    {}

func (m *FileStats) GetEntries() []*FileStat {
	if m != nil {
		return m.Entries
	}
	return nil
}

type GetRequest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}

func (m *GetRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type EmptyMessage struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}

type CopyOperation struct {
	LocalFileName    *string `protobuf:"bytes,1,opt,name=local_file_name" json:"local_file_name,omitempty"`
	RemoteLocation   *string `protobuf:"bytes,2,opt,name=remote_location" json:"remote_location,omitempty"`
	Upload           *bool   `protobuf:"varint,3,opt,name=upload" json:"upload,omitempty"`
	Checksum         *string `protobuf:"bytes,4,opt,name=checksum" json:"checksum,omitempty"`
	ModuleType       *string `protobuf:"bytes,5,opt,name=module_type" json:"module_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CopyOperation) Reset()         { *m = CopyOperation{} }
func (m *CopyOperation) String() string { return proto.CompactTextString(m) }
func (*CopyOperation) ProtoMessage()    {}

func (m *CopyOperation) GetLocalFileName() string {
	if m != nil && m.LocalFileName != nil {
		return *m.LocalFileName
	}
	return ""
}

func (m *CopyOperation) GetRemoteLocation() string {
	if m != nil && m.RemoteLocation != nil {
		return *m.RemoteLocation
	}
	return ""
}

func (m *CopyOperation) GetUpload() bool {
	if m != nil && m.Upload != nil {
		return *m.Upload
	}
	return false
}

func (m *CopyOperation) GetChecksum() string {
	if m != nil && m.Checksum != nil {
		return *m.Checksum
	}
	return ""
}

func (m *CopyOperation) GetModuleType() string {
	if m != nil && m.ModuleType != nil {
		return *m.ModuleType
	}
	return ""
}

type CopyOperations struct {
	Entries          []*CopyOperation `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	SandboxId        *string          `protobuf:"bytes,2,opt,name=sandbox_id" json:"sandbox_id,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *CopyOperations) Reset()         { *m = CopyOperations{} }
func (m *CopyOperations) String() string { return proto.CompactTextString(m) }
func (*CopyOperations) ProtoMessage()    {}

func (m *CopyOperations) GetEntries() []*CopyOperation {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *CopyOperations) GetSandboxId() string {
	if m != nil && m.SandboxId != nil {
		return *m.SandboxId
	}
	return ""
}

type NamePair struct {
	Source           *string `protobuf:"bytes,1,req,name=source" json:"source,omitempty"`
	Destination      *string `protobuf:"bytes,2,req,name=destination" json:"destination,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NamePair) Reset()         { *m = NamePair{} }
func (m *NamePair) String() string { return proto.CompactTextString(m) }
func (*NamePair) ProtoMessage()    {}

func (m *NamePair) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *NamePair) GetDestination() string {
	if m != nil && m.Destination != nil {
		return *m.Destination
	}
	return ""
}

type RepeatedNamePairEntries struct {
	Entries          []*NamePair `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	SandboxId        *string     `protobuf:"bytes,2,opt,name=sandbox_id" json:"sandbox_id,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *RepeatedNamePairEntries) Reset()         { *m = RepeatedNamePairEntries{} }
func (m *RepeatedNamePairEntries) String() string { return proto.CompactTextString(m) }
func (*RepeatedNamePairEntries) ProtoMessage()    {}

func (m *RepeatedNamePairEntries) GetEntries() []*NamePair {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *RepeatedNamePairEntries) GetSandboxId() string {
	if m != nil && m.SandboxId != nil {
		return *m.SandboxId
	}
	return ""
}

type RepeatedStringEntries struct {
	Entries          []string `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RepeatedStringEntries) Reset()         { *m = RepeatedStringEntries{} }
func (m *RepeatedStringEntries) String() string { return proto.CompactTextString(m) }
func (*RepeatedStringEntries) ProtoMessage()    {}

func (m *RepeatedStringEntries) GetEntries() []string {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterEnum("contester.proto.BinaryTypeResponse_Win32BinaryType", BinaryTypeResponse_Win32BinaryType_name, BinaryTypeResponse_Win32BinaryType_value)
}
