#!/bin/bash

set -e -u -x

cd $(dirname $0)/..

mkdir -p .goempty/src/github.com/vito
rm -rf .goempty/src/github.com/vito/houdini
ln -s $PWD .goempty/src/github.com/vito/houdini

truckers=$(gosub list -a ./cmd/houdini | grep -v houdini)
for trucker in $truckers; do
  GOPATH=$PWD/deps:$PWD/.goempty go get $trucker
done

gosub sync -g deps $truckers
