#!/bin/sh

set -e -x

export GOPATH=$PWD/gopath
export PATH=$PWD/bin:$PATH

export DISTDIR=$PWD/release

date +"%Y-%m-%d" > $DISTDIR/release-name

cd $GOPATH/src/github.com/vito/houdini

mkdir -p $DISTDIR/artifacts

export GOPATH=$PWD/deps:$GOPATH

GOOS=darwin GOARCH=amd64 \
  go build -o $DISTDIR/artifacts/houdini_darwin_amd64 ./cmd/houdini

GOOS=windows GOARCH=amd64 \
  go build -o $DISTDIR/artifacts/houdini_windows_amd64.exe ./cmd/houdini

GOOS=windows GOARCH=386 \
  go build -o $DISTDIR/artifacts/houdini_windows_386.exe ./cmd/houdini

GOOS=linux GOARCH=amd64 \
  go build -o $DISTDIR/artifacts/houdini_linux_amd64 ./cmd/houdini

GOOS=linux GOARCH=386 \
  go build -o $DISTDIR/artifacts/houdini_linux_386 ./cmd/houdini
