#!/bin/sh

set -e -x

export GOPATH=$PWD/gopath
export PATH=$PWD/bin:$PATH

export DISTDIR=$PWD/dist
mkdir -p $DISTDIR/artifacts

date +"%Y-%m-%d" > $DISTDIR/release-name

cd $GOPATH/src/github.com/vito/houdini

GOPATH=$PWD/Godeps_darwin/_workspace:$GOPATH GOOS=darwin GOARCH=amd64 \
  go build -o $DISTDIR/artifacts/houdini_darwin_amd64 ./cmd/houdini

GOPATH=$PWD/Godeps_windows/_workspace:$GOPATH GOOS=windows GOARCH=amd64 \
  go build -o $DISTDIR/artifacts/houdini-win64.exe ./cmd/houdini

GOPATH=$PWD/Godeps_windows/_workspace:$GOPATH GOOS=windows GOARCH=386 \
  go build -o $DISTDIR/artifacts/houdini-win32.exe ./cmd/houdini
