#!/bin/sh

set -e -x

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

export DISTDIR=$PWD/dist
mkdir -p $DISTDIR/artifacts

date +"%Y-%m-%d" > $DISTDIR/release-name

cd $GOPATH/src/github.com/vito/houdini

export GOPATH=$PWD/Godeps/_workspace:$GOPATH

GOOS=darwin GOARCH=amd64 go build -o $DISTDIR/artifacts/houdini_darwin_amd64 ./cmd/houdini
GOOS=windows GOARCH=amd64 go build -o $DISTDIR/artifacts/houdini.exe ./cmd/houdini
